### ISSUE TITLE
Dead Lectern crashed my game.

### ISSUE THREAD

**Issue by HauntedSniper** [Yamahari/ILikeWood-1.15#26] opened 2020-10-29 23:46 UTC
This would be the crash log:

Time: 10/29/20 5:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.func_200662_C(WoodenLecternTileEntity.java:30) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47) ~[?:8.0.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_612_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565) ~[?:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:559) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tileentity.LecternTileEntity.<init>(SourceFile:138) ~[?:?] {re:classloading}
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.<init>(WoodenLecternTileEntity.java:20) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at yamahari.ilikewood.registry.WoodenTileEntityTypes.lambda$null$5(WoodenTileEntityTypes.java:75) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at yamahari.ilikewood.registry.WoodenTileEntityTypes$$Lambda$11598/1653597866.get(Unknown Source) ~[?:?] {}
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at yamahari.ilikewood.block.WoodenLecternBlock.func_196283_a_(WoodenLecternBlock.java:39) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:178) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_180501_a(World.java:177) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:748) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.lambda$onItemUse$0(DeadlyHooks.java:121) ~[?:3.3.5] {re:classloading}
	at shadows.apotheosis.deadly.asm.DeadlyHooks$$Lambda$18411/915564158.apply(Unknown Source) ~[?:?] {}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:135) ~[?:3.3.5] {re:classloading}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:121) ~[?:3.3.5] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:add-spacing-for-stack,xf:fml:charm:ItemStack,xf:fml:apotheosis:apothitemusehook}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1174919051.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.func_200662_C(WoodenLecternTileEntity.java:30)
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47)
	at net.minecraftforge.eventbus.ASMEventHandler_612_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:559)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44)
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34)
	at net.minecraft.tileentity.LecternTileEntity.<init>(SourceFile:138)
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.<init>(WoodenLecternTileEntity.java:20)
	at yamahari.ilikewood.registry.WoodenTileEntityTypes.lambda$null$5(WoodenTileEntityTypes.java:75)
	at yamahari.ilikewood.registry.WoodenTileEntityTypes$$Lambda$11598/1653597866.get(Unknown Source)
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92)
	at yamahari.ilikewood.block.WoodenLecternBlock.func_196283_a_(WoodenLecternBlock.java:39)
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:178)
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288)
	at net.minecraft.world.World.func_180501_a(World.java:177)
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:748)
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146)
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54)
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39)
	at shadows.apotheosis.deadly.asm.DeadlyHooks.lambda$onItemUse$0(DeadlyHooks.java:121)
	at shadows.apotheosis.deadly.asm.DeadlyHooks$$Lambda$18411/915564158.apply(Unknown Source)
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:135)
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:121)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:300)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['RipHSniper'/233, l='MpServer', x=-79.13, y=4.00, z=-229.60]]
	Chunk stats: Client Chunk Cache: 841, 550
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -5907216894794857865
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-32,4,-256), Chunk: (at 0,0,0 in -2,-16; contains blocks -32,0,-256 to -17,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 520734 game time, 6187 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1174919051.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3523869632 bytes (3360 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.27.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		vanillaextension-1.15.2-1.0.3.jar Vanilla Extension {vanillaextension@1.15.2-1.0.3 DONE}
		roughmobsrevamped-1.15.2-4.1.2.jar Rough Mobs Revamped {roughmobsrevamped@version DONE}
		ElenaiDodge-1.15.2-1.7.0.jar Elenai Dodge {elenaidodge@1.15.2-1.7.0 DONE}
		flower-breeding-1.15.2-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
		deadlyendphantoms-1.15.2-1.01.jar Deadly End Phantoms {deadlyendphantoms@1.01 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.1.2.jar TerraForged {terraforged@0.1.2 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		Apotheosis-1.15.2-3.3.5.jar Apotheosis {apotheosis@3.3.5 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2 (1).jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2 (1).jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		SnowRealMagic-1.15.2-1.7.5 (1).jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		shetiphiancore-1.15-3.7.2.jar ShetiPhian-Core {shetiphiancore@3.7.2 DONE}
		respawnablepets-1.1.4.jar Respawnable Pets {respawnablepets@1.1.4 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		corpse-1.15.2-1.0.6.jar Corpse {corpse@1.15.2-1.0.6 DONE}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
		PeruMod1.0.1.jar Peru Mod {peru_mod@1.0.0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		BetterDrowning-1.15.2-1.0.3.jar BetterDrowning {betterdrowning@1.0.3 DONE}
		projectvibrantjourneys-1.15.2-2.0.4.jar Project: Vibrant Journeys {projectvibrantjourneys@1.15.2-2.0.4 DONE}
		masonry-1.15.2-0.3.4 (1).jar Masonry {masonry@NONE DONE}
		simplefarming-1.15.2-1.3.0.jar Simple Farming {simplefarming@1.15.1-1.3.0 DONE}
		xercamod-1.15.2-2.6.jar Xerca Mod {xercamod@1.15.2-2.6 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		horse_colors-1.15.2-1.4.0.1.jar Realistic Horse Genetics {horse_colors@1.15.2-1.4.0.1 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		Mushroom+Quest_1.15.2_v2.3.jar Mushroom Quest {mushroomquest@1.0.0 DONE}
		EndReborn+[0.6.1].jar End: Reborn {endreborn@0.6.1 DONE}
		lottaterracotta-1.15.2-1.3.1.jar Lotta Terracotta {lottaterracotta@1.15.2-1.3.1 DONE}
		SpartanWeaponry-1.15.2-2.0.0-beta-1.jar Spartan Weaponry {spartanweaponry@2.0.0 beta 1 DONE}
		furniture-7.0.0-pre16-1.15.1 (1).jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		productivebees-1.15.2-0.4.1.4.jar Productive Bees {productivebees@1.15.2-0.4.1.4 DONE}
		+skeleton-expansion-3.0.1_1.15.2.jar Skeleton Expansion+ {skeleton_expansion@1.0.0 DONE}
		More+Dogs+1.15.2-1.0.6.jar More Dog Breeds {moredogs@1.0.6 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		Craft_and_Hunt_V1.1.0_MC_1.15.2.jar Craft and Hunt {craftandhunt@0.9 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		Mexicraft+1.0.1.jar Mexicraft {mexicraft@1.0.1 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		OptiForge-MC1.15.2-0.1.27.jar OptiForge {optiforge@0.1.27 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		SneakyMagic-v2.0-1.15.2.jar Sneaky Magic {sneakymagic@2.0 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		WallpaperCraft-1.15.2-1.2.4.jar Wallpapercraft {wallpapercraft@1.2.4 DONE}
		WallpapercraftSlabs-1.15.2-1.1.0.jar Wallpapercraft - Slabs! {wallpapercraftslabs@1.1.0 DONE}
		WallpapercraftStairs-1.15.2-1.1.1.jar Wallpapercraft - Stairs {wallpapercraftstairs@1.1.1 DONE}
		sweetconcrete-1.15.2-1.7.1.jar Sweet Concrete {sweetconcrete@1.15.2-1.7.1 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		EnhancedVanilla_Snapshot_20w27a-Forge-1.15.2.31.2.0.jar Enhanced Vanilla {enhancedvanilla@Snapshot 20w27a DONE}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
		iceandfire-2.1.0-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		beyond_the_nether_wastes_v_1.1.0.jar Beyond The Nether Wastes {btnw@1.0.0 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		goprone-1.15.x-1.3.0.jar GoProne {goprone@1.15.x-1.3.0 DONE}
		Bones-1.15.2-1.3.2.jar Bones {bones@1.15.2-1.3.2 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.6.4b.jar CoFH Core {cofh_core@0.6.4b DONE}
		ensorcellation-1.15.2-0.6.0b.jar Ensorcellation {ensorcellation@0.6.0b DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		packedup-1.0.18-mc1.15.jar PackedUp {packedup@1.0.18 DONE}
		archers_paradox-1.15.2-0.6.0b.jar Archer's Paradox {archers_paradox@0.6.0b DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 DONE}
		multibeds-1.15-1.6.1.jar Multi-Beds {multibeds@1.6.1 DONE}
		AutoRegLib-1.5-40 (1).jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 DONE}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 DONE}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 DONE}
		lanterncolors-1.15.2-1.0.1.jar Lantern Colors {lanterncolors@1.15.2-1.0.1 DONE}
		Regrowth-1.15.2-1.1.0.14.jar Regrowth Mod {regrowth@1.1.0.14 DONE}
		WorldEdit-CUI-FE3-1.15.2-3.0.5 (1).jar WorldEdit CUI Forge Edition 3 {worldeditcuife3@3.0.5 DONE}
		worldedit-forge-mc1.15.2-7.1.0 (1).jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		mobcatcher-2.2 (1).jar Mob Catcher {mobcatcher@2.2 DONE}
		DamageTilt-1.15-forge-0.1.1.jar DamageTilt {damagetilt@0.1.1 DONE}
		ilikewood-1.15.2-2.2.2.0 (2).jar I Like Wood {ilikewood@1.15.2-2.2.2.0 DONE}
		Aquaculture-1.15.2-2.0.20.jar Aquaculture 2 {aquaculture@1.15.2-2.0.20 DONE}
		ExtendedNetherBackport-1.15.2-Beta-4.1.2.jar Extended Nether Backport {extendednether@4.1.2 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Launched Version: 1.15.2-forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/Drago's Creepy Mobs (incompatible), file/RSRecolor Green, file/Tom's Biome Mobs, file/bettervanillabuilding (incompatible), file/Creatures+, file/Thorolhugil's Cute Squids (incompatible), file/Haston's Foxes, file/PupleDrago (incompatible)
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by Yamahari** [comment] 2020-11-01 16:43
thx for reporting, looks like a duplicate of #12  
the issue is with cooking for blockheads and my mod x) still havent fixed that as the fix would probably break all existing lectern

**Closed as completed by Yamahari** 2020-11-01 16:43 UTC
